title: <p align="center"> Ajay Kumar Dabral </p>
logo: /assets/img/for_profile.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ajay-kumar-dabral-b4227622b">LinkedIn</a> |
  <a href="https://github.com/AjayDabral">GitHub</a>
  
  <br>   
  I'm working on Python, Kernel Development, Schematic Design of PCBs, .
  Also working on Machine learning & NLP related problems.
  Working in Bharat Electronics Limited in Design and Development Department as Senior Engineer.
  <br>
  </p>



theme: jekyll-theme-minimal
